
[audits]

[[audits.futures]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
version = "0.3.32"
notes = "Full audit"

[[audits.futures-channel]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
version = "0.3.32"
notes = "Full audit"

[[audits.futures-core]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
version = "0.3.13"
notes = "Full audit"

[[audits.futures-core]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.13 -> 0.3.32"

[[audits.futures-io]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
version = "0.3.32"
notes = "Full audit"

[[audits.futures-sink]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
version = "0.3.32"
notes = "Full audit"

[[audits.futures-task]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
version = "0.3.32"
notes = "Full audit"

[[audits.ipnet]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
delta = "2.11.0 -> 2.12.0"

[[audits.lru]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
delta = "0.16.2 -> 0.16.3"
notes = "No unsafe differences from v0.16.2"

[[audits.uniffi_pipeline]]
who = "Yuki Kishimoto <yukikishimoto@protonmail.com>"
criteria = "safe-to-deploy"
delta = "0.31.0 -> 0.31.1"
